name: Update LeetCode Badges

on:
  push:
    branches:
      - main

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Update to use latest version (v3)

      - name: Set up Python
        uses: actions/setup-python@v2  # Update to use latest version (v3)
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run Python Script to Update Badges
        run: python update_badges.py
